### ISSUE TITLE
Qué se debe hacer cuando se termina el juego?

### ISSUE THREAD

**Issue by Merok23** [Merok23/TPG-Taller-Left4dead-Grupo1#52]
Definir un comprotamiento para cuando el juego termina en cuanto a game loop y a cuando a conexiones.

**Comment by nathencinoza** [comment]
Cuando el game loop popea un estado de game state, y tiene true en game over el hilo de partida de detiene. Cuando se van saliendo los jugadores, se chequea si el juego esta vacio, en ese caso se elimina la partida del mapa de partidas de game handler.
